### PR TITLE
Playground for CI

### LINKED ISSUE #2: Move all active development to GitHub
Following actions are tight with Gerrit:

- Tags, this is ok
- Brew builds, has to be replaced by something else or create proxy
- Valgrind, can be moved
- Test suite, can be moved
- Tito, can be moved
- Probably pooling into prod?

### PR DESCRIPTION
**Pull request by StykMartin**
Closes #2 
Signed-off-by: Martin Styk <mastyk@redhat.com>

### CODE REVIEW

**Comment by TomasTomecek** [comment]
The SRPM creation problem should be resolved by https://github.com/packit-service/packit/pull/698

**Comment by StykMartin** [comment]
Rawhide is failing again !? BAD RAWHIDE BAD

**Comment by StykMartin** [comment]
@ernestask hehehe

**Comment by ernestask** [comment]
/👀

**Comment by StykMartin** [comment]
@renanrodrigo Tiger is running

**Comment by ernestask** [comment]
What tiger? There is only Dolphin.

**Comment by renanrodrigo** [comment]
@ernestask was sucesfully tigered

**Comment by ernestask** [comment]
Only collaborators can trigger @ernestask.

**Comment by renanrodrigo** [comment]
@ernestask ano prosím

**Comment by StykMartin** [comment]
@renanrodrigo @danrodrig take a look. CI looks fine.
/:eyes:

**Comment by StykMartin** [comment]
@beaker-project/restraint-maintainers Any objections? I guess this will close the whole workflow and nothing is blocking us anymore from migrating to GitHub with Restraint

**Comment by MartinBasti** [comment]
￼/:eyes:

**Comment by StykMartin** [comment]
@MartinBasti /👀

**Comment by MartinBasti** [comment]
/👀

**Comment by MartinBasti** [comment]
/👁

**Comment by MartinBasti** [comment]
/👀

**Pull request closed without merging**
