### PR TITLE
Fix: Upgrade restraint with glib 2.68

### PR DESCRIPTION
**Pull request by cbouchar**
Seeing lots of build issues with glib. Time to upgrade.

Issue: 9

### CODE REVIEW

**Comment by cbouchar** [comment]
This should have been in draft mode.  Looking to convert.

**Comment by cbouchar** [comment]
@StykMartin @renanrodrigo With what I've committed, I would expect ALL distros to fail to build since g_memdup is not supported in glib release 2.68.  What magic am I missing so it recognizes my changes?  When I tried this manually by running 
tito build --test --srpm, it wasn't finding glib-2.56 and when I looked at the spec file from the tar file, it did not contain my change.  Any hints would be appreciated.

**Comment by StykMartin** [comment]
You can't really.
This was the purpose of dolphin and this is something that I mentioned. Upstream builds are created against packages needed but with the version given in Fedora / RHEL repos. So third-party changes will not affect any of the builds you can see here.

BREW can answer this question.

I will take a look if we can mimic our third-party included builds here in upstream, but it will be complicated because we have a lot of stuff in chroots.

**Review by StykMartin — CHANGES_REQUESTED** [review]
This is not going to work.

1. EL5 and EL6 will be out of the game.
2. Changes made here are not sufficient. We didn't swap to the new glib because they introduced meson. You will fail to compile this w/ static build.

**Comment by ernestask** [comment]
I was messing with this during the weekend, can share my changes later.

**Comment by StykMartin** [comment]
We can drop this PR. It will be handled in #197

**Pull request closed without merging**
