### PR TITLE
Add eng-fedora-34/Drop eng-fedora-31 to release tags

### PR DESCRIPTION
**Pull request by cbouchar**
Adding new rawhide (future 34). This changeset is pending creation
of f34 chroot.

Closes: 159

### CODE REVIEW

**Comment by cbouchar** [comment]
I meant to mark this as draft as we are still waiting for f34 chroots to be created before this can move forward.  I believe this change is needed in order for https://github.com/beaker-project/beaker-project.org/pull/28 to be successful.

**Comment by StykMartin** [comment]
> I meant to mark this as draft as we are still waiting for f34 chroots to be created before this can move forward. I believe this change is needed in order for [beaker-project/beaker-project.org#28](https://github.com/beaker-project/beaker-project.org/pull/28) to be successful.

Actually no.

You don't want to go that road. Instead of that you should create build for given branch in dist git directly.
And use this target when you will be working on next release. Otherwise, you will screw NVR for no reason.

**Review by StykMartin — APPROVED** [review]

**Comment by cbouchar** [comment]
> > I meant to mark this as draft as we are still waiting for f34 chroots to be created before this can move forward. I believe this change is needed in order for [beaker-project/beaker-project.org#28](https://github.com/beaker-project/beaker-project.org/pull/28) to be successful.
> 
> Actually no.
> 
> You don't want to go that road. Instead of that you should create build for given branch in dist git directly.
> And use this target when you will be working on next release. Otherwise, you will screw NVR for no reason.

I believe you are asking me to do the following:  (BTW what does NVR stand for?)

# Wait for ticket to complete which creates tags for eng-fedora-34, then Skip restraint tito procedure and go directly to rhpkg
rhpkg clone restraint
# check if eng-fedora-34 branch is present
git checkout eng-fedora-34
# if yes, check that sources and restraint.spec files matches other branches.
rhpkg build

**Comment by cbouchar** [comment]
You think we should create a release-note informing folks that eng-fedora-31 images will be dropped?

**Comment by StykMartin** [comment]
> You think we should create a release-note informing folks that eng-fedora-31 images will be dropped?

You don't really need to. Restraint is always built for current distros

**Review by StykMartin — APPROVED** [review]

**Review by StykMartin — APPROVED** [review]

**Comment by cbouchar** [comment]
Martin:  Just an FYI, we're waiting for others teams (rhpkg tool) to provide image for f34.

**Comment by StykMartin** [comment]
> Martin: Just an FYI, we're waiting for others teams (rhpkg tool) to provide image for f34.

Not sure if I understand this correctly.
The *only* thing you really need is to have **eng-fedora-34** on place and that's it.

If **eng-fedora-34** exists, then you have dist-git and everything what is really needed.

I shouldn't wait till someone will create any other builds for you.

**Comment by cbouchar** [comment]
> > Martin: Just an FYI, we're waiting for others teams (rhpkg tool) to provide image for f34.
> 
> Not sure if I understand this correctly.
> The _only_ thing you really need is to have **eng-fedora-34** in place and that's it.
> 
> If **eng-fedora-34** exists, then you have dist-git and everything that is really needed.
> 
> You shouldn't wait till someone will create any other builds for you.

When I try to perform my own build using 'rhpkg clone restraint; rhpkg switch-branch eng-fedora-34;rhpkg build --scratch', the output in Brew shows rhpkg failure.   I'm using --scratch initially to be safe.
    _DEBUG util.py:556: Downloading Packages:DEBUG
    util.py:554: BUILDSTDERR: Error: Error downloading packages:DEBUG
    util.py:554: BUILDSTDERR: Status code: 404 for http://kojipkgs01.iad2.fedoraproject.org/compose/rawhide/latest-Fedora-Rawhide/compose/Everything/ppc64le/os/Packages/b/binutils-2.35.1-4.fc34.ppc64le.rpm (IP: 10.3.169.106)DEBUG
util.py:698: Child return code was: 1_
    I created a ticket about this and they said rhpkg needs to be built for f34. I'm open to any other suggestions?

**Comment by StykMartin** [comment]
This is not what error is saying.
Only 2 things can be broken in this case.
1. Repo for Rawhide is messed up
2. Repo is not regenerated properly therefore DNF will ask for file which is not there, resulting in 404.

I would guess the second is the right answer.

**Comment by cbouchar** [comment]
> This is not what error is saying.
> Only 2 things can be broken in this case.
> 
> 1. Repo for Rawhide is messed up
> 2. Repo is not regenerated properly therefore DNF will ask for file which is not there, resulting in 404.
> 
> I would guess the second is the right answer.

I filed a case with the dist-git/brew team. I believe this problem is in their arena.  I'm not sure what else I can do.
Someone in that team pointed to rhpkg and rhpkg puts dependency on other tools.  If I build outside of rhpkd restraint repo using tito, it was successful.  Perhaps I can point this out to them.

**Comment by StykMartin** [comment]
> > This is not what error is saying.
> > Only 2 things can be broken in this case.
> > 
> > 1. Repo for Rawhide is messed up
> > 2. Repo is not regenerated properly therefore DNF will ask for file which is not there, resulting in 404.
> > 
> > I would guess the second is the right answer.
> 
> I filed a case with the dist-git/brew team. I believe this problem is in their arena. I'm not sure what else I can do.
> Someone in that team pointed to rhpkg and rhpkg puts dependency on other tools. If I build outside of rhpkd restraint repo using tito, it was successful. Perhaps I can point this out to them.

Error posted by you has nothing to do with any tooling. 
Chroot needed binutils-2.35.1-4.fc34.ppc64le.rpm package from given repo. And repo responded with 404.

https://http.cat/404

**Comment by cbouchar** [comment]
I will share this information with dist-git team with fingers crossed that
we can move forward.

**Pull request merged**
